In [1]:
#Notebook 5.Mice
import seaborn as sns
import pandas as pd
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

In [2]:
titanic = sns.load_dataset('titanic')
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [3]:
print(titanic.isnull().sum())

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [4]:
data = titanic[['age','fare','pclass','sex']]
data = pd.get_dummies(data, drop_first=True)

In [5]:
data.head()

    age     fare  pclass  sex_male
0  22.0   7.2500       3      True
1  38.0  71.2833       1     False
2  26.0   7.9250       3     False
3  35.0  53.1000       1     False
4  35.0   8.0500       3      True

In [6]:
imputer = IterativeImputer(max_iter=10, random_state=0)

In [7]:
data_imputed = pd.DataFrame(imputer.fit_transform(data), columns=data.columns)

In [8]:
print("Datos originales:\n",data.head(6))
print("\nDatos imputados:\n",data_imputed.head(6))

Datos originales:
     age     fare  pclass  sex_male
0  22.0   7.2500       3      True
1  38.0  71.2833       1     False
2  26.0   7.9250       3     False
3  35.0  53.1000       1     False
4  35.0   8.0500       3      True
5   NaN   8.4583       3      True

Datos imputados:
          age     fare  pclass  sex_male
0  22.000000   7.2500     3.0       1.0
1  38.000000  71.2833     1.0       0.0
2  26.000000   7.9250     3.0       0.0
3  35.000000  53.1000     1.0       0.0
4  35.000000   8.0500     3.0       1.0
5  26.082704   8.4583     3.0       1.0

In [17]:
life_expectancy = pd.read_csv('Life_Expectancy_Data.csv')

In [18]:
life_expectancy.head()

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,Afghanistan,2015,Developing,65.0,263.0,62,0.01,71.279624,65.0,1154,...,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,Afghanistan,2014,Developing,59.9,271.0,64,0.01,73.523582,62.0,492,...,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,Afghanistan,2013,Developing,59.9,268.0,66,0.01,73.219243,64.0,430,...,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,Afghanistan,2012,Developing,59.5,272.0,69,0.01,78.184215,67.0,2787,...,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,Afghanistan,2011,Developing,59.2,275.0,71,0.01,7.097109,68.0,3013,...,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5

In [25]:
life_expectancy  = life_expectancy.drop(['Country','Status'], axis=1)

In [26]:
print(life_expectancy.isnull().sum())

Year                                 0
Life expectancy                     10
Adult Mortality                     10
infant deaths                        0
Alcohol                            194
percentage expenditure               0
Hepatitis B                        553
Measles                              0
 BMI                                34
under-five deaths                    0
Polio                               19
Total expenditure                  226
Diphtheria                          19
 HIV/AIDS                            0
GDP                                448
Population                         652
 thinness  1-19 years               34
 thinness 5-9 years                 34
Income composition of resources    167
Schooling                          163
dtype: int64

In [27]:
imputer = IterativeImputer(max_iter=10, random_state=0)

In [29]:
life_expectancy_imputed = pd.DataFrame(imputer.fit_transform(life_expectancy), columns=life_expectancy.columns)

In [30]:
print("Datos originales:\n",life_expectancy.head(6))
print("\nDatos imputados:\n",life_expectancy_imputed.head(6))

Datos originales:
    Year  Life expectancy   Adult Mortality  infant deaths  Alcohol  \
0  2015              65.0            263.0             62     0.01
1  2014              59.9            271.0             64     0.01
2  2013              59.9            268.0             66     0.01
3  2012              59.5            272.0             69     0.01
4  2011              59.2            275.0             71     0.01
5  2010              58.8            279.0             74     0.01

   percentage expenditure  Hepatitis B  Measles    BMI   under-five deaths   \
0               71.279624         65.0      1154   19.1                  83
1               73.523582         62.0       492   18.6                  86
2               73.219243         64.0       430   18.1                  89
3               78.184215         67.0      2787   17.6                  93
4                7.097109         68.0      3013   17.2                  97
5               79.679367         66.0      1989   16.7                 102

   Polio  Total expenditure  Diphtheria    HIV/AIDS         GDP  Population  \
0    6.0               8.16         65.0        0.1  584.259210  33736494.0
1   58.0               8.18         62.0        0.1  612.696514    327582.0
2   62.0               8.13         64.0        0.1  631.744976  31731688.0
3   67.0               8.52         67.0        0.1  669.959000   3696958.0
4   68.0               7.87         68.0        0.1   63.537231   2978599.0
5   66.0               9.20         66.0        0.1  553.328940   2883167.0

    thinness  1-19 years   thinness 5-9 years  \
0                   17.2                 17.3
1                   17.5                 17.5
2                   17.7                 17.7
3                   17.9                 18.0
4                   18.2                 18.2
5                   18.4                 18.4

   Income composition of resources  Schooling
0                            0.479       10.1
1                            0.476       10.0
2                            0.470        9.9
3                            0.463        9.8
4                            0.454        9.5
5                            0.448        9.2

Datos imputados:
      Year  Life expectancy   Adult Mortality  infant deaths  Alcohol  \
0  2015.0              65.0            263.0           62.0     0.01
1  2014.0              59.9            271.0           64.0     0.01
2  2013.0              59.9            268.0           66.0     0.01
3  2012.0              59.5            272.0           69.0     0.01
4  2011.0              59.2            275.0           71.0     0.01
5  2010.0              58.8            279.0           74.0     0.01

   percentage expenditure  Hepatitis B  Measles    BMI   under-five deaths   \
0               71.279624         65.0    1154.0   19.1                83.0
1               73.523582         62.0     492.0   18.6                86.0
2               73.219243         64.0     430.0   18.1                89.0
3               78.184215         67.0    2787.0   17.6                93.0
4                7.097109         68.0    3013.0   17.2                97.0
5               79.679367         66.0    1989.0   16.7               102.0

   Polio  Total expenditure  Diphtheria    HIV/AIDS         GDP  Population  \
0    6.0               8.16         65.0        0.1  584.259210  33736494.0
1   58.0               8.18         62.0        0.1  612.696514    327582.0
2   62.0               8.13         64.0        0.1  631.744976  31731688.0
3   67.0               8.52         67.0        0.1  669.959000   3696958.0
4   68.0               7.87         68.0        0.1   63.537231   2978599.0
5   66.0               9.20         66.0        0.1  553.328940   2883167.0

    thinness  1-19 years   thinness 5-9 years  \
0                   17.2                 17.3
1                   17.5                 17.5
2                   17.7                 17.7
3                   17.9                 18.0
4                   18.2                 18.2
5                   18.4                 18.4

   Income composition of resources  Schooling
0                            0.479       10.1
1                            0.476       10.0
2                            0.470        9.9
3                            0.463        9.8
4                            0.454        9.5
5                            0.448        9.2

In [ ]:
Planets seaborn